import styles from './Table.module.css'
import CheckBox from './CheckBox'

const Table = ({ title, viewPatientFicha, setPreferredDay, preferredDay }) => {

    return (
      <div className={styles.table_container}>
        <h3>{title} *</h3>
        <div className={styles.table}>
          <table>
            <thead>
              <tr>
                <th>Turno</th>
                <th>Segunda</th>
                <th>Terça</th>
                <th>Quarta</th>
                <th>Quinta</th>
                <th>Sexta</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Manhã</td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.morning_monday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.morning_tuesday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.morning_wednesday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.morning_thursday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.morning_friday"
                    text=""
                  />
                </td>
              </tr>
              <tr>
                <td>Tarde</td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.afternoon_monday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.afternoon_tuesday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.afternoon_wednesday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.afternoon_thursday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.afternoon_friday"
                    text=""
                  />
                </td>
              </tr>
              <tr>
                <td>Noite</td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.night_monday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.night_tuesday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.night_wednesday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.night_thursday"
                    text=""
                  />
                </td>
                <td>
                  <CheckBox
                    disabled={viewPatientFicha}
                    customClass="table"
                    name="preferred_day.night_friday"
                    text=""
                  />
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    );
}

export default Table